### ISSUE TITLE
About fastfading 

### ISSUE THREAD

**Issue by ibrahimth** [WhiteGrayxp/MARL-based-Dec-Spectrum-Access#1]
Hi there,
I found that [in the core file line 59](https://github.com/WhiteGrayxp/MARL-based-Dec-Spectrum-Access/blob/2e284bd592ae3d212f34ea577de94d1ac67a8496/Baseline/env/core.py#L59) that you use   `+ self.fastfading ` while in the MARLspectrumSharingV2X code they use `- self.fastfading`. I'm really confused.

**Comment by WhiteGrayxp** [comment]
The multiplication operation will become an addition operation (unit in dB) when in logarithmic representation mode, and the fading components, i.e., the slow fading component which is lognormally distributed and the fast fading which closely follows Rayleigh distribution, here are all expressed in dB. So I think it is more reasonable to a "+" operation here.

You can also refer to this article: [Fast Fading Mobile Channel Modeling for Wireless Communication](https://www.sciencedirect.com/science/article/pii/S1877050916306159).

**Comment by WhiteGrayxp** [comment]
> The multiplication operation will become an addition operation (unit in dB) when in logarithmic representation mode, and the fading components, i.e., the slow fading component which is lognormally distributed and the fast fading which closely follows Rayleigh distribution, here are all expressed in dB. So I think it is more reasonable to a "+" operation here.
> 
> You can also refer to this article: [Fast Fading Mobile Channel Modeling for Wireless Communication](https://www.sciencedirect.com/science/article/pii/S1877050916306159).
> 
> #1

**Comment by WhiteGrayxp** [comment]
> Hi there, I found that [in the core file line 59](https://github.com/WhiteGrayxp/MARL-based-Dec-Spectrum-Access/blob/2e284bd592ae3d212f34ea577de94d1ac67a8496/Baseline/env/core.py#L59) that you use `+ self.fastfading ` while in the MARLspectrumSharingV2X code they use `- self.fastfading`. I'm really confused.

The multiplication operation will become an addition operation (unit in dB) when in logarithmic representation mode, and the fading components, i.e., the slow fading component which is lognormally distributed and the fast fading which closely follows Rayleigh distribution, here are all expressed in dB. So I think it is more reasonable to a "+" operation here.

You can also refer to this article: [Fast Fading Mobile Channel Modeling for Wireless Communication](https://www.sciencedirect.com/science/article/pii/S1877050916306159).

**Comment by ibrahimth** [comment]
Thanks for the info.

**Comment by ibrahimth** [comment]
I changed it to be
`self.V2V_channels_with_fastfading = V2V_channels_with_fastfading + 20 * np.log10(
            np.abs(np.random.normal(0, 1, V2V_channels_with_fastfading.shape) + 1j * np.random.normal(0, 1,
                                                                                                     V2V_channels_with_fastfading.shape)) / math.sqrt(
                2))`
